language: go
go:
  - 1.5.3

branches:
  except:
    - master # This is the original fork
    - original # This is also the original fork

# before_script:
#   - rm -rf $HOME/gopath/src/github.com/back4app/parse-cli
#   - ln -s $HOME/gopath/src/github.com/back4app/parse-cli $HOME/gopath/src/github.com/back4app/parse-cli

script:
  - go test -v ./...
before_deploy:
  - go get github.com/inconshreveable/mousetrap # temporary fix for travis build breaks for windows due to cobra dependency on mousetrap
  - GOOS=darwin GOARCH=amd64 go build -o b4a -v github.com/back4app/parse-cli
  - GOOS=windows GOARCH=386 go build -o b4a.exe -v github.com/back4app/parse-cli
  - GOOS=linux GOARCH=386 go build -o b4a_linux -v github.com/back4app/parse-cli
  - GOOS=linux GOARCH=arm go build -o b4a_linux_arm -v github.com/back4app/parse-cli
deploy:
  provider: releases
  api_key:
    secure: "CJMqOWtrUzSAjY3jif+jIU/dlocZ+2ylAgRcPq7JV6yPM3/XyZ8i09lkzM7IrGL/KQd9ZvDuyLHAJJTtzuvgOTc8QtJLrS88hj/5lE/6uahJ8F63SlLJJ3RFPsV0DPVMpP65Azl+poZBLsjrbjaj2AlAYJl1j2FVd8CxfMIrGaLbnQARhU+HgDukrXTpIf9GMOHeEat8/oORPXpahQwfoZDb8WXZIYnG/SLZDegzZMb+281ErzLcaSfZrBnKGSPbidZQvdBYwZQqRNTXN+PLHIdMqaVckilpHi3uh4McTLs9hu8TiwxxZWFvhH4BA8BG/pcKZ6hAJXseHiOef7WAII6Btb3gE7SSKTuH0DFsEa0LvUhW1se/MTOOMxhVaSSxskpNG1UUFnQXpdabKMP9N7ZbTT7SOpMZsEsGdHPh6P9lJ5OsVogo+YLABEqgAHWtuXWBj1/g0iWUglaCBPQZcdOJWd8C0bYHsEAk+O+SovtFKXPSKtEh6OJajv+8K63GRrpnQvlMQcXg6PKlFMJBr8atpcOpdV6Ld3yFHIO0kTaEn2uZc3j5yt2GVS4M3wEpQ/eeFns6asEXg2gkwQgQh68Dc1jSoKMy/4ffbCV4LHEJn0QnowZ+T4gb4wXLIsYVFCX020HZbqA3gnJoRkgdh1P5HHr7fyN+gQPWHOnDHto="

  file:
    - b4a
    - b4a.exe
    - b4a_linux
    - b4a_linux_arm
  skip_cleanup: true
  on:
    repo: back4app/parse-cli
    tags: true
    condition: $TRAVIS_TAG =~ ^release_.*
