language: go
go:
  - 1.5.3
script:
  - go test -v ./...
before_deploy:
  - go get github.com/inconshreveable/mousetrap # temporary fix for travis build breaks for windows due to cobra dependency on mousetrap
  - GOOS=darwin GOARCH=amd64 go build -o back4app -v github.com/back4app/parse-cli
  - GOOS=windows GOARCH=386 go build -o back4app.exe -v github.com/back4app/parse-cli
  - GOOS=linux GOARCH=386 go build -o back4app_linux -v github.com/back4app/parse-cli
  - GOOS=linux GOARCH=arm go build -o back4app_linux_arm -v github.com/back4app/parse-cli
deploy:
  provider: releases
  file:
    - back4app
    - back4app.exe
    - back4app_linux
    - back4app_linux_arm
  skip_cleanup: true
  on:
    repo: luisholanda/parse-cli
    tags: true
    condition: $TRAVIS_TAG =~ ^release_.*
