language: go
go:
  - 1.9
script:
  - go test -v ./...
before_deploy:
  - go get github.com/inconshreveable/mousetrap # temporary fix for travis build breaks for windows due to cobra dependency on mousetrap
  - GOOS=darwin GOARCH=amd64 go build -o b4a -v github.com/back4app/parse-cli
  - GOOS=windows GOARCH=386 go build -o b4a.exe -v github.com/back4app/parse-cli
  - GOOS=linux GOARCH=386 go build -o b4a_linux -v github.com/back4app/parse-cli
  - GOOS=linux GOARCH=arm go build -o b4a_linux_arm -v github.com/back4app/parse-cli
  - cp b4a parse
  - cp b4a.exe parse.exe
  - cp b4a_linux parse_linux
  - cp b4a_linux_arm parse_linux_arm
deploy:
  provider: releases
  api_key:
    secure: "cScpWXV2YJks73QCzlamJDJ8BF9IPy1etoRq1rGRswdGWUHgfZeWyq9GHZTdWuWPcnHe6jk79jULOuKO80W9zHplC5O3gOB1eOHFK5tQHU3V+sdQFl+fWCbctnvgsvSpCq6nuXObUX65XAF5nWV2r2s0g3cLtKyn0icABHAhXZlIAp8ChMxQQuczmFxYpsCTtv9AzHqjSO6WZza7iloZQKDSugMSfvArCYLwUDYikWMgWOPnM6XDsXNkFCJPsZbZWBB28bLDBycrhuiqLL1eIyCb5RCnfY73ViNYPy1XAUyzF8I59mthSN83Ng/x/fUKB0ezEExnJLhvK9oMXXFhidupQNO9dziqm/Sb7YMJagC4LrVaqTP/pORPEfUq/UFe4SSEomGdevuipZRwDVRS3Hke5p9qs1ZlC/YshiCyR2ifkgfXHIXFPFE20em6m7lfz7XQ2cM2brAZLrjh1jL3P0BeIBcnJbnbNnyet5dZxANi6xD7RrDi0SF5vy5SMbhRyk5MjU4A4GcpZvWMj21ttA1siVbUGOg9qtKFVdnIpHff4EJZKvyfG6OCjySdKNAhrRJmz/VkTEvGtv7Q4CyM2RZZ/YYF0/2fukWAU4roqGoH9vWjCYXphG5cl1Jax3bo42OIhMHPZz6/ahP3NMSdMByAOyASkyC6oW8uxRjzwQw="

  file:
    - b4a
    - b4a.exe
    - b4a_linux
    - b4a_linux_arm
    - parse
    - parse.exe
    - parse_linux
    - parse_linux_arm
  skip_cleanup: true
  on:
    repo: back4app/parse-cli
    tags: true
    condition: $TRAVIS_TAG =~ ^release_.*
